import {
  CreatorEntity,
  DividendPaymentEntity,
  DividendRoundEntity,
  IPOEntity,
  IPOPurchaseEntity,
  PriceHistoryEntity,
  TradeEntity,
  TransactionEntity,
  UserEntity,
  TABLE,
} from "../src/db/index.js";

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

const users = [
  {
    userId: "seed_user_investor",
    email: "investor@zeedly.dev",
    role: "user" as const,
    openfortUserId: "seed_openfort_investor",
    solanaPubkey: "9xQeWvG816bUx9EPjHmaT23yvVM2ZWu8uJ8vZ4xF4q1D",
    kycStatus: "verified" as const,
    kycUpdatedAt: now - 6 * day,
  },
  {
    userId: "seed_user_admin",
    email: "admin@zeedly.dev",
    role: "admin" as const,
    openfortUserId: "seed_openfort_admin",
    kycStatus: "verified" as const,
    kycUpdatedAt: now - 20 * day,
  },
  {
    userId: "seed_user_creator",
    email: "creator@zeedly.dev",
    role: "creator" as const,
    openfortUserId: "seed_openfort_creator",
    kycStatus: "pending" as const,
    kycUpdatedAt: now - 2 * day,
  },
];

const creators = [
  {
    creatorId: "seed_creator_lena_lens",
    userId: "seed_user_creator",
    slug: "lena-lens",
    name: "Lena Lens",
    avatarUrl: image("photo-1494790108377-be9c29b29330"),
    artworkUrl: image("photo-1516035069371-29a1b244cc32"),
    bio: "Documentary filmmaker building a premium travel and street photography channel with recurring sponsors and paid education products.",
    background:
      "Lena has grown through long-form field guides, Lightroom preset launches, and brand integrations with travel gear partners. Proceeds fund a 12-month creator studio and expanded production team.",
    category: "Photography",
    tags: ["Travel", "Cameras", "Education"],
    genre: "Documentary photography",
    youtubeUrl: "https://youtube.com/@lena-lens",
    subscriberCount: 1260000,
    avgViews: 212000,
    totalViews: 194000000,
    uploadFrequency: "3 uploads per month",
    monthlyRevenue: 82000,
    estimatedMonthlyDividend: 8200,
    valuation: 1800000,
    revenueShareBps: 1000,
    analytics: {
      subscriberHistory: [
        { label: "Oct", value: 980000 },
        { label: "Nov", value: 1040000 },
        { label: "Dec", value: 1110000 },
        { label: "Jan", value: 1175000 },
        { label: "Feb", value: 1210000 },
        { label: "Mar", value: 1260000 },
      ],
      subscriberProjection: [
        { label: "Now", value: 1260000 },
        { label: "+3m", value: 1390000 },
        { label: "+6m", value: 1540000 },
        { label: "+9m", value: 1710000 },
        { label: "+12m", value: 1900000 },
      ],
    },
    tokenMint: "LENAdev11111111111111111111111111111111111",
    status: "live" as const,
  },
  {
    creatorId: "seed_creator_studio_nova",
    slug: "studio-nova",
    name: "Studio Nova",
    avatarUrl: image("photo-1527980965255-d3b416303d12"),
    artworkUrl: image("photo-1492684223066-81342ee5ff30"),
    bio: "A music production collective turning weekly beat breakdowns into a subscription education funnel and sample-pack business.",
    background:
      "Studio Nova monetizes through YouTube, sample packs, paid mix reviews, and partner drops with creator hardware brands.",
    category: "Music",
    tags: ["Production", "Education", "Samples"],
    genre: "Music production",
    youtubeUrl: "https://youtube.com/@studio-nova",
    subscriberCount: 684000,
    avgViews: 98000,
    totalViews: 76000000,
    uploadFrequency: "Weekly uploads",
    monthlyRevenue: 54000,
    estimatedMonthlyDividend: 5400,
    valuation: 1250000,
    revenueShareBps: 1000,
    analytics: {
      subscriberHistory: [
        { label: "Oct", value: 510000 },
        { label: "Nov", value: 548000 },
        { label: "Dec", value: 590000 },
        { label: "Jan", value: 623000 },
        { label: "Feb", value: 655000 },
        { label: "Mar", value: 684000 },
      ],
    },
    status: "live" as const,
  },
  {
    creatorId: "seed_creator_gridiron_lab",
    slug: "gridiron-lab",
    name: "Gridiron Lab",
    avatarUrl: image("photo-1568602471122-7832951cc4c5"),
    artworkUrl: image("photo-1521412644187-c49fa049e84d"),
    bio: "Data-led football analysis channel covering tactics, player valuation, and weekly film-room breakdowns.",
    background:
      "Revenue comes from sponsors, a paid newsletter, live watch parties, and data-tool subscriptions for serious fans.",
    category: "Sports",
    tags: ["Football", "Analytics", "Tactics"],
    genre: "Sports analysis",
    youtubeUrl: "https://youtube.com/@gridiron-lab",
    subscriberCount: 438000,
    avgViews: 146000,
    totalViews: 59000000,
    uploadFrequency: "2 videos per week",
    monthlyRevenue: 46000,
    estimatedMonthlyDividend: 4600,
    valuation: 980000,
    revenueShareBps: 1000,
    tokenMint: "GRIDdev11111111111111111111111111111111111",
    status: "live" as const,
  },
  {
    creatorId: "seed_creator_quiet_kitchen",
    slug: "quiet-kitchen",
    name: "Quiet Kitchen",
    avatarUrl: image("photo-1438761681033-6461ffad8d80"),
    artworkUrl: image("photo-1495521821757-a1efb6729352"),
    bio: "Calm cooking videos, recipe memberships, and premium pantry partnerships for a loyal home-cooking audience.",
    background:
      "The raise funds a second shooting kitchen, recipe testing assistant, and the first run of branded pantry staples.",
    category: "Food",
    tags: ["Cooking", "Lifestyle", "Recipes"],
    genre: "Cooking",
    youtubeUrl: "https://youtube.com/@quiet-kitchen",
    subscriberCount: 905000,
    avgViews: 185000,
    totalViews: 121000000,
    uploadFrequency: "4 uploads per month",
    monthlyRevenue: 61000,
    estimatedMonthlyDividend: 6100,
    valuation: 1420000,
    revenueShareBps: 1000,
    status: "live" as const,
  },
  {
    creatorId: "seed_creator_calm_code",
    slug: "calm-code",
    name: "Calm Code",
    avatarUrl: image("photo-1500648767791-00dcc994a43e"),
    artworkUrl: image("photo-1515879218367-8466d910aaa4"),
    bio: "Developer education channel focused on concise app builds and technical explainers.",
    background: "Awaiting final review before an offering can be launched.",
    category: "Tech",
    tags: ["Coding", "SaaS", "Education"],
    youtubeUrl: "https://youtube.com/@calm-code",
    subscriberCount: 312000,
    avgViews: 74000,
    totalViews: 33000000,
    monthlyRevenue: 29000,
    revenueShareBps: 800,
    status: "approved" as const,
  },
  {
    creatorId: "seed_creator_mira_moves",
    slug: "mira-moves",
    name: "Mira Moves",
    avatarUrl: image("photo-1534528741775-53994a69daeb"),
    artworkUrl: image("photo-1518611012118-696072aa579a"),
    bio: "Dance creator application with strong short-form reach and a growing long-form audience.",
    background: "Pending admin review.",
    category: "Dance",
    tags: ["Dance", "Fitness", "Shorts"],
    youtubeUrl: "https://youtube.com/@mira-moves",
    subscriberCount: 522000,
    avgViews: 160000,
    totalViews: 88000000,
    monthlyRevenue: 38000,
    revenueShareBps: 900,
    status: "pending" as const,
  },
];

const ipos = [
  {
    ipoId: "seed_ipo_lena_2026",
    creatorId: "seed_creator_lena_lens",
    pricePerToken: 10,
    totalSupply: 10000,
    sold: 10000,
    raisedUsd: 100000,
    raiseTargetUsd: 100000,
    maxInvestmentPerAccountUsd: 10000,
    valuationAtRaise: 1800000,
    dividendCadence: "Quarterly",
    tokenMintedAt: now - 25 * day,
    tokenDispersedAt: now - 24 * day,
    completedAt: now - 25 * day,
    status: "closed" as const,
    startsAt: now - 55 * day,
    endsAt: now - 25 * day,
  },
  {
    ipoId: "seed_ipo_gridiron_2026",
    creatorId: "seed_creator_gridiron_lab",
    pricePerToken: 8.5,
    totalSupply: 20000,
    sold: 20000,
    raisedUsd: 170000,
    raiseTargetUsd: 170000,
    maxInvestmentPerAccountUsd: 15000,
    valuationAtRaise: 980000,
    dividendCadence: "Monthly",
    tokenMintedAt: now - 12 * day,
    tokenDispersedAt: now - 11 * day,
    completedAt: now - 12 * day,
    status: "closed" as const,
    startsAt: now - 42 * day,
    endsAt: now - 12 * day,
  },
  {
    ipoId: "seed_ipo_studio_nova_2026",
    creatorId: "seed_creator_studio_nova",
    pricePerToken: 5,
    totalSupply: 50000,
    sold: 18200,
    raisedUsd: 91000,
    raiseTargetUsd: 250000,
    maxInvestmentPerAccountUsd: 12500,
    valuationAtRaise: 1250000,
    dividendCadence: "Quarterly",
    status: "active" as const,
    startsAt: now - 7 * day,
    endsAt: now + 23 * day,
  },
  {
    ipoId: "seed_ipo_quiet_kitchen_2026",
    creatorId: "seed_creator_quiet_kitchen",
    pricePerToken: 6.25,
    totalSupply: 32000,
    sold: 0,
    raisedUsd: 0,
    raiseTargetUsd: 200000,
    maxInvestmentPerAccountUsd: 10000,
    valuationAtRaise: 1420000,
    dividendCadence: "Quarterly",
    status: "upcoming" as const,
    startsAt: now + 10 * day,
    endsAt: now + 40 * day,
  },
];

const purchases = [
  {
    purchaseId: "seed_purchase_lena_claimed",
    ipoId: "seed_ipo_lena_2026",
    userId: "seed_user_investor",
    quantity: 80,
    usdAmount: 800,
    asset: "USDT",
    transactionId: "seed_tx_lena_purchase",
    claimedAt: now - 18 * day,
    txSig: "claim_seed_lena_001",
    status: "claimed" as const,
  },
  {
    purchaseId: "seed_purchase_studio_locked",
    ipoId: "seed_ipo_studio_nova_2026",
    userId: "seed_user_investor",
    quantity: 150,
    usdAmount: 750,
    asset: "USDT",
    transactionId: "seed_tx_studio_locked",
    status: "locked" as const,
  },
];

const transactions = [
  {
    txId: "seed_tx_deposit_usd",
    userId: "seed_user_investor",
    type: "deposit" as const,
    amount: 5000,
    asset: "USDT",
    fiatAmount: 5000,
    fiatCurrency: "USD",
    exchangeRate: 1,
    referenceId: "seed_stripe_pi_usd",
    status: "confirmed" as const,
  },
  {
    txId: "seed_tx_deposit_gbp",
    userId: "seed_user_investor",
    type: "deposit" as const,
    amount: 1250,
    asset: "USDT",
    fiatAmount: 1000,
    fiatCurrency: "GBP",
    exchangeRate: 1.25,
    referenceId: "seed_stripe_pi_gbp",
    status: "confirmed" as const,
  },
  {
    txId: "seed_tx_lena_purchase",
    userId: "seed_user_investor",
    type: "ipo_purchase" as const,
    amount: -800,
    asset: "USDT",
    referenceId: "seed_purchase_lena_claimed",
    txSig: "claim_seed_lena_001",
    status: "confirmed" as const,
  },
  {
    txId: "seed_tx_studio_locked",
    userId: "seed_user_investor",
    type: "ipo_purchase" as const,
    amount: -750,
    asset: "USDT",
    referenceId: "seed_purchase_studio_locked",
    status: "pending" as const,
  },
  {
    txId: "seed_tx_dividend_lena",
    userId: "seed_user_investor",
    type: "dividend" as const,
    amount: 42.5,
    asset: "USDT",
    referenceId: "seed_dividend_payment_lena",
    txSig: "div_seed_lena_001",
    status: "confirmed" as const,
  },
];

const trades = [
  {
    tradeId: "seed_trade_lena_buy_1",
    userId: "seed_user_investor",
    creatorId: "seed_creator_lena_lens",
    side: "buy" as const,
    quantity: 25,
    usdAmount: 312.5,
    price: 12.5,
    fee: 3.13,
    txSig: "trade_seed_lena_001",
    status: "confirmed" as const,
  },
  {
    tradeId: "seed_trade_grid_buy_1",
    userId: "seed_user_investor",
    creatorId: "seed_creator_gridiron_lab",
    side: "buy" as const,
    quantity: 40,
    usdAmount: 380,
    price: 9.5,
    fee: 3.8,
    txSig: "trade_seed_grid_001",
    status: "confirmed" as const,
  },
  {
    tradeId: "seed_trade_lena_market_1",
    userId: "seed_user_admin",
    creatorId: "seed_creator_lena_lens",
    side: "buy" as const,
    quantity: 60,
    usdAmount: 825,
    price: 13.75,
    fee: 8.25,
    txSig: "trade_seed_lena_market_001",
    status: "confirmed" as const,
  },
  {
    tradeId: "seed_trade_grid_market_1",
    userId: "seed_user_creator",
    creatorId: "seed_creator_gridiron_lab",
    side: "buy" as const,
    quantity: 120,
    usdAmount: 1320,
    price: 11,
    fee: 13.2,
    txSig: "trade_seed_grid_market_001",
    status: "confirmed" as const,
  },
];

const priceHistory = [
  ...[10, 10.4, 11.1, 11.8, 12.5, 13.75].map((price, index) => ({
    priceId: `seed_price_lena_${index + 1}`,
    creatorId: "seed_creator_lena_lens",
    price,
    timestamp: now - (30 - index * 5) * day,
  })),
  ...[8.5, 8.9, 9.4, 10.2, 10.6, 11].map((price, index) => ({
    priceId: `seed_price_grid_${index + 1}`,
    creatorId: "seed_creator_gridiron_lab",
    price,
    timestamp: now - (18 - index * 3) * day,
  })),
  {
    priceId: "seed_price_studio_initial",
    creatorId: "seed_creator_studio_nova",
    price: 5,
    timestamp: now - 7 * day,
  },
];

const dividendRounds = [
  {
    roundId: "seed_dividend_round_lena_2026_04",
    creatorId: "seed_creator_lena_lens",
    period: "2026-04",
    totalUsdc: 5300,
    snapshotData: { tokenSupply: 10000, revenueShareBps: 1000 },
    distributedAt: now - 5 * day,
  },
];

const dividendPayments = [
  {
    paymentId: "seed_dividend_payment_lena",
    roundId: "seed_dividend_round_lena_2026_04",
    userId: "seed_user_investor",
    tokenBalanceAtSnapshot: 80,
    usdcAmount: 42.5,
    txSig: "div_seed_lena_001",
  },
];

async function seed() {
  await Promise.all([
    UserEntity.put(users).go(),
    CreatorEntity.put(creators).go(),
    IPOEntity.put(ipos).go(),
    IPOPurchaseEntity.put(purchases).go(),
    TransactionEntity.put(transactions).go(),
    TradeEntity.put(trades).go(),
    PriceHistoryEntity.put(priceHistory).go(),
    DividendRoundEntity.put(dividendRounds).go(),
    DividendPaymentEntity.put(dividendPayments).go(),
  ]);

  console.log(
    JSON.stringify(
      {
        table: TABLE,
        seeded: {
          users: users.length,
          creators: creators.length,
          ipos: ipos.length,
          purchases: purchases.length,
          transactions: transactions.length,
          trades: trades.length,
          priceHistory: priceHistory.length,
          dividendRounds: dividendRounds.length,
          dividendPayments: dividendPayments.length,
        },
      },
      null,
      2,
    ),
  );
}

seed().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
