export const env = {
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001/trpc",
  NEXT_PUBLIC_OPENFORT_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_OPENFORT_PUBLISHABLE_KEY ?? "",
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY ?? "",
};
